(c-define-type GLenum unsigned-int)
(c-define-type GLboolean int)
(c-define-type GLbitfield unsigned-int)
(c-define-type GLbyte signed-char)
(c-define-type GLshort short)
(c-define-type GLint int)
(c-define-type GLsizei int)
(c-define-type GLubyte unsigned-int8)
(c-define-type GLushort unsigned-short)
(c-define-type GLuint unsigned-int)
(c-define-type GLfloat float)
(c-define-type GLclampf float)
(c-define-type GLvoid void)
(c-define-type GLfixed int)
(c-define-type GLclampx int)
(c-define-type GLintptr int)
(c-define-type GLsizeiptr int)

(c-define-type GLfloat* (pointer GLfloat))
(c-define-type GLuint* (pointer GLuint))
(c-define-type GLushort* (pointer GLushort))
(c-define-type GLubyte* (pointer GLubyte))
